version: '3.9'
services:
  frontend:
    container_name: voting-frontend
    build: ./frontend
    restart: 'always'
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 30s
      retries: 5
    networks:
      - bbb
  backend:
    container_name: voting-backend
    build: ./backend
    restart: 'always'
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=VOTING
      - DB_PORT=3306
      - JWT_SECRET=secret
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 30s
      retries: 5
    networks:
      - bbb
  db:
    image: mysql:8.0.21
    container_name: voting-database
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    networks:
      - bbb
  rabbitmq:
    image: rabbitmq:3.8.5-management-alpine
    container_name: voting-rabbitmq
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_PASS=password"
      - "RABBITMQ_DEFAULT_USER=username"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - bbb
networks:
  bbb:
    driver: bridge